### ISSUE TITLE
Makefile does not recognize CentOS Stream 8 as EL8

### ISSUE THREAD

**Issue by opoplawski** [OpenVPN/ovpn-dco#32]
The check is:
```
cat /etc/redhat-release 2>/dev/null | grep -c " 8."
```
but /etc/redhat-release has:
```
CentOS Stream release 8
```
without a trailing `.` so it fails.

**Comment by pjperry** [comment]
That's probably a good thing as the CentOS Stream 8 kernel if not the same as the RHEL 8 kernel.

CentOS Stream 8 kernel is essentially a rolling development kernel of what the next RHEL kernel will look like in 6 months time with lots of stuff backported. They should be treated as two separate distinct distros/kernels.

A better way would be to use the defines that RHEL already provides within the source, but that won't solve the CentOS Stream issue. For example,

#if RHEL_MAJOR == 8
#define EL8
#elif RHEL_MAJOR == 9
#define EL9
#endif

**Comment by ordex** [comment]
> That's probably a good thing as the CentOS Stream 8 kernel if not the same as the RHEL 8 kernel.
> 
> CentOS Stream 8 kernel is essentially a rolling development kernel of what the next RHEL kernel will look like in 6 months time with lots of stuff backported. They should be treated as two separate distinct distros/kernels.
> 
> A better way would be to use the defines that RHEL already provides within the source, but that won't solve the CentOS Stream issue. For example,
> 
> #if RHEL_MAJOR == 8 #define EL8 #elif RHEL_MAJOR == 9 #define EL9 #endif

should we truly expect more features to be backported within a major release? or can we assume that once RHEL8 is out, following CentOS kernel releases are only about bugfixes?
In the latter case, it still makes sense to treat CentOS8 as RHEL8. Otherwise, this is going to be messy because it's basically impossible to ensure ovpn-dco will always compile against a certain CentOS release.
