### ISSUE TITLE
Backport from linux-kernel-ovpn

### ISSUE THREAD

**Issue by LGA1150** [OpenVPN/ovpn-dco#70]
Hi, I noticed you have created a new repo [linux-kernel-ovpn](https://github.com/OpenVPN/linux-kernel-ovpn) and [sent the patch upstream](https://lore.kernel.org/netdev/20241002-b4-ovpn-v8-0-37ceffcffbde@openvpn.net/), with some bug fixes and improvements which this out-of-tree dco module does not have.

Are you planning on backporting those changes here?

**Comment by ordex** [comment]
Hi @LGA1150 and thanks for your interest!
First of all, please be aware that that version of the kernel module is still under development and its APIs are still unstable (under review/correction right now).

Secondly, yes, there will be a backported version but I am planning to go through the backports project, rather than maintaining a full out-of-tree repository.

This repo will then be deprecated.

**Comment by ordex** [comment]
I am closing this ticket as this is not a real issue, but just a question.
Feel free to continue the discussion on IRC or on the mailing list if needed.

Thanks!

**Comment by LGA1150** [comment]
I see. Thanks for your quick reply.

> its APIs are still unstable (under review/correction right now).
Do you mean the new module will be incompatible with OpenVPN 2.6?

**Comment by ordex** [comment]
> Do you mean the new module will be incompatible with OpenVPN 2.6?

Correct. Support for the new module will be integrated in OpenVPN 2.7

**Comment by LGA1150** [comment]
Okay, got it.
